# docker-compose.yml
version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - TERM=xterm-256color
    env_file:
      - .env
    tty: true
    volumes:
      - ./backend:/usr/src/app
    links:
      - database
    command: bash -c "
      sqlx migrate run && 
      cargo watch -x \"test -- --nocapture\""
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: "postgres:15.3"
    ports:
      - "${DB_PORT}:${INTERNAL_DB_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5