[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "=0.5.0-rc.3", features = ["secrets", "json"] }
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.1.0", features = ["postgres"] }
dotenv = "0.15.0"
rocket_oauth2 = { git = "https://github.com/jebrosen/rocket_oauth2", branch = "next" }
reqwest = { version = "0.11", features = ["json"] }

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.3"
default-features = false
features = ["diesel_postgres_pool"]