DROP FUNCTION IF EXISTS manage_updated_at(_tbl regclass);
DROP FUNCTION IF EXISTS set_updated_at();



DROP EXTENSION IF EXISTS "uuid-ossp";

DROP TABLE TABLE IF EXISTS actions;
DROP TABLE TABLE IF EXISTS task_labels;
DROP TABLE TABLE IF EXISTS labels;
DROP TABLE TABLE IF EXISTS task_relations;
DROP TABLE TABLE IF EXISTS tasks;
DROP TABLE TABLE IF EXISTS list_relations;
DROP TABLE TABLE IF EXISTS lists;
DROP TABLE TABLE IF EXISTS discord_user_login;
DROP TABLE TABLE IF EXISTS email_user_logins;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;